steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - build
  - -t
  - us-central1-docker.pkg.dev/$PROJECT_ID/octopus/$REPO_NAME-api
  - -f
  - Dockerfile.api
  - .
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - build
  - -t
  - us-central1-docker.pkg.dev/$PROJECT_ID/octopus/$REPO_NAME-router
  - -f
  - Dockerfile.gateway
  - .
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - build
  - -t
  - us-central1-docker.pkg.dev/$PROJECT_ID/octopus/$REPO_NAME-fluentd
  - -f
  - Dockerfile.kafka
  - .
images:
- us-central1-docker.pkg.dev/$PROJECT_ID/octopus/$REPO_NAME-api
- us-central1-docker.pkg.dev/$PROJECT_ID/octopus/$REPO_NAME-router
- us-central1-docker.pkg.dev/$PROJECT_ID/octopus/$REPO_NAME-fluentd
