steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - build
  - -t
  - us-central1-docker.pkg.dev/$PROJECT_ID/octopus/$REPO_NAME-api
  - -f
  - Dockerfile.api
  - .
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - build
  - -t
  - us-central1-docker.pkg.dev/$PROJECT_ID/octopus/$REPO_NAME-messenger
  - -f
  - Dockerfile.messenger
  - .
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - build
  - -t
  - us-central1-docker.pkg.dev/$PROJECT_ID/octopus/$REPO_NAME-stat
  - -f
  - Dockerfile.stat
  - .
images:
- us-central1-docker.pkg.dev/$PROJECT_ID/octopus/$REPO_NAME-api
- us-central1-docker.pkg.dev/$PROJECT_ID/octopus/$REPO_NAME-messenger
- us-central1-docker.pkg.dev/$PROJECT_ID/octopus/$REPO_NAME-stat
