##
## Build
##
FROM golang:1.17-bullseye AS build

WORKDIR /go/src/app

ADD ./api /go/src/app

RUN go get -d -v ./...

RUN go build -o /go/bin/api

##
## Deploy
##
FROM gcr.io/distroless/base-debian11

WORKDIR /octopus-gateway

COPY --from=build /go/bin/api /octopus-gateway/api

EXPOSE 80

ENTRYPOINT ["/octopus-gateway/api"]
