apiVersion: v1
kind: ConfigMap
metadata:
  name: api-dev-config
data:
  dev.env.json: |
    {
      "name": "elara",
      "port": 7003,
      "messengers": {
        "testnet": ["ws://octopus-gateway-messenger:7004"]
      },
      "pubsub": {
        "topic": "gateway-dev",
        "subscription": "gateway-dev-sub"
      },
      "pool": 10,
      "statServer": "octopus-gateway-stat:7002"
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopus-gateway-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octopus-gateway-api
  template:
    metadata:
      labels:
        app: octopus-gateway-api
    spec:
      containers:
      - name: octopus-gateway-api
        image: asia-northeast1-docker.pkg.dev/orbital-builder-316023/docker-repository/octopus-gateway-api:0.0.1
        ports:
        - containerPort: 7003
        volumeMounts:
        - name: api-config
          mountPath: /app/api/config/env
      volumes:
      - name: api-config
        configMap:
          name: api-dev-config

---
apiVersion: v1
kind: Service
metadata:
  name: octopus-gateway-api
spec:
  type: LoadBalancer
  selector:
    app: octopus-gateway-api
  ports:
  - port: 80
    targetPort: 7003
    protocol: TCP