apiVersion: v1
kind: ConfigMap
metadata:
  name: messenger-dev-config
data:
  dev.env.json: |
    {
      "name": "messenger",
      "port": 7004,
      "chain": {
        "testnet": {
          "rpc": ["http://dl-testnet:9933"],
          "ws": ["ws://dl-testnet:9944"],
          "processors": ["node", "cache"]
        }
      },
      "pool": 1
    }

---
apiVersion: v1
data:
  testnet.json: |
    {
      "processor": {
        "cache": [
          "system_name",
          "system_version",
          "system_chain",
          "system_chainType",
          "system_properties",
          "system_networkState",
          "author_pendingExtrinsics",
          "chain_getHeader", 
          "chain_getBlock", 
          "chain_getBlockHash", 
          "chain_getFinalizedHead",
          "state_getMetadata", 
          "state_getRuntimeVersion", 
          "system_peers",
          "system_syncState",
          "system_health",
          "rpc_methods"
        ],
        "subscription": [
          "state_subscribeStorage",
          "state_unsubscribeStorage",
          "chain_subscribeNewHeads",
          "chain_unsubscribeNewHeads",
          "chain_subscribeAllHeads",
          "chain_unsubscribeAllHeads",
          "chain_subscribeFinalizedHeads",
          "chain_unsubscribeFinalizedHeads"
        ],
        "history": [
        ]
      }
    }
kind: ConfigMap
metadata:
  name: messenger-chain-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopus-gateway-messenger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octopus-gateway-messenger
  template:
    metadata:
      labels:
        app: octopus-gateway-messenger
    spec:
      containers:
      - name: octopus-gateway-messenger
        image: asia-northeast1-docker.pkg.dev/orbital-builder-316023/docker-repository/octopus-gateway-messenger:0.0.1
        ports:
        - containerPort: 7004
        volumeMounts:
        - name: messenger-config
          mountPath: /app/messenger/config/env
        - name: messenger-chain
          mountPath: /app/messenger/config/testnet.json
          subPath: testnet.json
      volumes:
      - name: messenger-config
        configMap:
          name: messenger-dev-config
      - name: messenger-chain
        configMap:
          name: messenger-chain-config
          items:
          - key: testnet.json
            path: testnet.json

---
apiVersion: v1
kind: Service
metadata:
  name: octopus-gateway-messenger
spec:
  type: ClusterIP
  selector:
    app: octopus-gateway-messenger
  ports:
  - port: 7004
    targetPort: 7004