FROM node:16.6.1-buster-slim

WORKDIR /app

COPY ./lib ./lib
RUN cd /app/lib && npm install --only=production

COPY ./api ./api
RUN cd /app/api && npm install --only=production

CMD ["node", "api/app.js"]
