FROM node:16.3.0-buster-slim

WORKDIR /app

COPY ./lib ./lib
RUN cd /app/lib && npm install --only=production

COPY ./messenger ./messenger
RUN cd /app/messenger && npm install --only=production

CMD ["node", "messenger/app.js"]
